# Generated by Django 5.1.1 on 2024-09-09 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
